# Generated by Django 3.0.4 on 2020-03-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotee_detail',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
