# Generated by Django 3.0.5 on 2020-05-11 09:21

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('NA', 'Do not know')], default='NA', max_length=3)),
                ('dob', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='Male', max_length=6)),
                ('marital_status', models.CharField(choices=[('BRA', 'Brahmachari'), ('GRA', 'Grahastha'), ('VAN', 'Vanaprastha'), ('SAN', 'Sannyasi')], default='BRA', max_length=12)),
                ('mobile_no', models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('whatsapp_no', models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('present_address', models.CharField(max_length=250, null=True)),
                ('permanent_address', models.CharField(max_length=250, null=True)),
                ('father_name', models.CharField(max_length=100, null=True)),
                ('father_mobile_no', models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mother_name', models.CharField(max_length=100, null=True)),
                ('mother_mobile_no', models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('brother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_sister', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brother_name', models.CharField(max_length=100)),
                ('year_of_birth', models.IntegerField(validators=[django.core.validators.MinValueValidator(1960), user.models.max_value_current_year], verbose_name='year')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
    ]
