# Generated by Django 3.0.5 on 2020-05-11 09:27

import django.core.validators
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='year_of_birth',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1960), user.models.max_value_current_year], verbose_name='Birth year'),
        ),
    ]
