# Generated by Django 3.0.5 on 2020-05-12 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20200511_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brother',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='brother_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name_of_sister',
        ),
        migrations.AddField(
            model_name='brother',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
