# Generated by Django 3.0.5 on 2020-04-30 10:05

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_of_brother',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age_of_sister',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_mobile_no',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact Father number', max_length=31),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact mobile number', max_length=31),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_mobile_no',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact Mother number', max_length=31),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_of_brother',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_of_sister',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='permanent_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='present_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact WhatsApp number', max_length=31),
        ),
    ]
