# Generated by Django 3.0.6 on 2020-05-30 11:53

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_auto_20200530_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of Company/Institute/Organization')),
                ('post', models.CharField(blank=True, max_length=50, null=True, verbose_name='Post/Position/Profile')),
                ('salary_pa', models.IntegerField(blank=True, null=True, verbose_name='Salary per annum')),
                ('salary_pm', models.IntegerField(blank=True, null=True, verbose_name='Salary per month')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation', models.CharField(choices=[('btech', 'B.Tech'), ('Be', 'BE'), ('Bsc', 'B.Sc.'), ('Dip', 'Diploma')], max_length=10, null=True)),
                ('stream', models.CharField(max_length=50, null=True)),
                ('year_of_passout', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1960), user.models.max_value_current_year], verbose_name='Year of Passout')),
                ('college', models.CharField(choices=[('iitbhu', 'IIT BHU'), ('iitk', 'IIT Kanpur'), ('bhu', 'BHU'), ('nit', 'NIT ALD'), ('iiit', 'IIIT ALD'), ('hbtu', 'HBTU'), ('iet', 'IET'), ('csjm', 'CSJM'), ('aith', 'AITH'), ('gcti', 'GCTI'), ('psit', 'PSIT'), ('rec', 'REC-Bijnore'), ('other', 'Other')], max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='devotional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_introduce', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1960), user.models.max_value_current_year], verbose_name='Year of introduction to ISKCON')),
                ('who_introduce', models.CharField(max_length=50, null=True, verbose_name='Who introduced you to ISKCON')),
                ('counselor', models.CharField(max_length=50, null=True, verbose_name='Counselor or Care Taker devotee from ISKCON, to whom you are connected)')),
                ('japa_rounds', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(16)], verbose_name='Number of rounds chanting')),
                ('started_japa', models.DateField(default=datetime.datetime.now, verbose_name='Chanting Since (Month and Year)')),
                ('started_16japa', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Chanting 16 rounds since (Month and Year)')),
                ('category', models.CharField(choices=[('gs', 'Voice GS'), ('ns', 'Voice NS'), ('pre', 'Prerna')], max_length=10, null=True, verbose_name='Category')),
                ('initiated_name', models.CharField(max_length=100, null=True, verbose_name='Initiated Name (if initiated)')),
                ('sm_name', models.CharField(help_text='Spiritual Master (if initiated) or aspiring spiritual master (if not initiated)', max_length=100, null=True, verbose_name='Spiritual Master')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
