# Generated by Django 3.0.7 on 2020-06-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200617_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotional',
            name='started_japa',
            field=models.DateField(null=True, verbose_name='Chanting Since (Month and Year)'),
        ),
    ]
