# Generated by Django 3.0.7 on 2020-06-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200617_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotional',
            name='started_16japa',
            field=models.DateField(blank=True, null=True, verbose_name='Chanting 16 rounds since (Month and Year)'),
        ),
    ]
